write-kubeconfig-mode: "0644"

%{ if length(token) > 0 }
token: ${token}
%{ endif }

%{ if length(tls_san) > 0 }
tls-san:
%{ for san in tls_san }
- ${san}
%{ endfor }
%{ endif }

%{ if server_taint }
node-taint:
- "CriticalAddonsOnly=true:NoExecute"
%{ endif }

%{ if length(disabled_server_charts) > 0 }
disable:
%{ for chart in disabled_server_charts }
- ${chart}
%{ endfor }
%{ endif }

etcd-s3: true
etcd-s3-bucket: ${bucket_name}
etcd-s3-region: ${bucket_region}
etcd-s3-folder: etcd-backup
etcd-snapshot-schedule-cron: "0 0 * * *"
etcd-snapshot-retention: 14
