apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  bootstrap: true
  repo: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
  chart: aws-ebs-csi-driver 
  targetNamespace: kube-system
%{ if aws_ebs_csi_driver != "latest" }
  version: ${aws_ebs_csi_driver}
%{ endif }
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  encrypted: "true"
---
