#cloud-config
%{ if length(extra_ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in extra_ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
runcmd:
- |
  case "${os_type}" in
  "Ubuntu")
    apt-get update && sudo apt-get install -y iptables python3-pip
    pip3 install awscli
    ;;
  "openSUSE")
    mkdir /tmp/ssm
    (
      cd /tmp/ssm; \
      wget https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm; \
      rpm --install amazon-ssm-agent.rpm; \
    )
    systemctl enable amazon-ssm-agent
    systemctl start amazon-ssm-agent
    ;;
  esac

- mkdir -p /etc/rancher/rke2
- aws s3 cp s3://${bucket}/config/setup-agent.sh /etc/rancher/rke2/
- bash /etc/rancher/rke2/setup-agent.sh "${startup}" "${os_type}"
