#cloud-config
%{ if length(extra_ssh_keys) > 0 }
ssh_authorized_keys:
%{ for ssh_key in extra_ssh_keys }
- ${ssh_key}
%{ endfor }
%{ endif }
runcmd:
- apt-get update && sudo apt-get install -y apt-transport-https gnupg2 jq iptables
- apt-get install -y python3-pip
- pip3 install awscli

- mkdir -p /etc/rancher/rke2
- aws s3 cp s3://${bucket}/config/setup-seed.sh /etc/rancher/rke2/
- bash /etc/rancher/rke2/setup-seed.sh
